version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: cvilo_postgres
    environment:
      POSTGRES_DB: cvilo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cvilo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cvilo-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Go API Service
  cvilo-api:
    image: ghcr.io/smhnaqvi/cveeker/cvilo-api:latest
    ports:
      - "8081:8081"
    environment:
      - GIN_MODE=release
    volumes:
      - /app/tmp
    networks:
      - cvilo-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # React Client Dashboard
  cvilo-clientarea:
    image: ghcr.io/smhnaqvi/cveeker/cvilo-clientarea:latest
    ports:
      - "3009:3009"
    volumes:
      - ./cvilo-clientarea:/app
      - /app/node_modules
    depends_on:
      - cvilo-api
    networks:
      - cvilo-network
    restart: unless-stopped

  # Next.js Landing Page
  cvilo-landing-nextjs:
    image: ghcr.io/smhnaqvi/cveeker/cvilo-landing-nextjs:latest
    ports:
      - "3001:3001"
    depends_on:
      - cvilo-api
    networks:
      - cvilo-network
    restart: unless-stopped

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cvilo_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cvilo.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - cvilo-network
    restart: unless-stopped

networks:
  cvilo-network:
    driver: bridge

volumes:
  app-data:
  postgres_data:
  pgadmin_data: 