/**
 * Print utilities for resume printing
 */

import type { ResumeFormValues } from "../../pages/dashboard/resume/components/ResumeForm";

export interface PrintOptions {
  title?: string;
  filename?: string;
  showHeader?: boolean;
  showFooter?: boolean;
}

/**
 * Opens the print dialog for the resume
 */
export function printResume(elementId: string, options: PrintOptions = {}) {
  const element = document.getElementById(elementId);
  if (!element) {
    console.error('Element not found for printing');
    return;
  }

  // Create a new window for printing
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    console.error('Could not open print window');
    return;
  }

  // Get the element's HTML content
  const content = element.innerHTML;

  // Create the print document
  const printDocument = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${options.title || 'Resume'}</title>
      <meta charset="utf-8">
      <style>
        @page {
          size: A4;
          margin: 20mm;
        }
        
        @media print {
          body {
            margin: 0;
            padding: 0;
          }
          
          /* Preserve all colors in print - make it colorful! */
          * {
            -webkit-print-color-adjust: exact !important;
            color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          
          .no-print {
            display: none !important;
          }
        }
        
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          line-height: 1.4;
          background: white;
        }
        
        .resume-container {
          max-width: 210mm;
          margin: 0 auto;
          padding: 0;
        }
        
        .print-header {
          text-align: center;
          margin-bottom: 20px;
          font-size: 12px;
          color: #666;
          border-bottom: 1px solid #ddd;
          padding-bottom: 10px;
        }
        
        .print-footer {
          text-align: center;
          margin-top: 20px;
          font-size: 10px;
          color: #666;
          border-top: 1px solid #ddd;
          padding-top: 10px;
        }
        
        .page-break {
          page-break-before: always;
        }
        
        .avoid-break {
          page-break-inside: avoid;
        }
        
        .force-break {
          page-break-before: always;
        }

        /* Ensure theme colors are preserved */
        .resume-preview {
          background: white;
        }

        .resume-preview * {
          -webkit-print-color-adjust: exact !important;
          color-adjust: exact !important;
          print-color-adjust: exact !important;
        }
      </style>
    </head>
    <body>
      <div class="resume-container">
        ${options.showHeader ? `
          <div class="print-header">
            <strong>${options.title || 'Professional Resume'}</strong>
            <br>
            Generated on ${new Date().toLocaleDateString()}
          </div>
        ` : ''}
        
        <div class="resume-content">
          ${content}
        </div>
        
        ${options.showFooter ? `
          <div class="print-footer">
            <strong>${options.title || 'Resume'}</strong> - Page 1
            <br>
            Generated by CVilo Resume Builder
          </div>
        ` : ''}
      </div>
    </body>
    </html>
  `;

  // Write the content to the print window
  printWindow.document.write(printDocument);
  printWindow.document.close();

  // Wait for content to load, then print
  printWindow.onload = () => {
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 500);
  };
}

/**
 * Downloads the resume as a PDF (requires browser print to PDF)
 */
export function downloadResumeAsPDF(elementId: string, options: PrintOptions = {}) {
  const filename = options.filename || 'resume.pdf';
  
  // Create a temporary link to trigger download
  const link = document.createElement('a');
  link.href = `javascript:printResume('${elementId}', ${JSON.stringify(options)})`;
  link.download = filename;
  link.click();
}

/**
 * Generates a print-friendly version of the resume
 */
export function createPrintFriendlyResume(data: ResumeFormValues, theme: string = 'modern-blue') {
  // This function can be used to create a print-optimized version
  // of the resume data with proper formatting
  return {
    ...data,
    theme,
    printMode: true,
  };
}

/**
 * Print styles for different themes
 */
export const printStyles = {
  'modern-blue': {
    backgroundColor: '#ffffff',
    color: '#2c3e50',
    accentColor: '#3498db',
  },
  'classic-dark': {
    backgroundColor: '#ffffff', // Force white for print
    color: '#000000',
    accentColor: '#e74c3c',
  },
  'creative-gradient': {
    backgroundColor: '#ffffff', // Force white for print
    color: '#000000',
    accentColor: '#ffd700',
  },
  'minimalist-gray': {
    backgroundColor: '#ffffff',
    color: '#495057',
    accentColor: '#007bff',
  },
  'professional-green': {
    backgroundColor: '#ffffff',
    color: '#2d3748',
    accentColor: '#38a169',
  },
  'elegant-purple': {
    backgroundColor: '#ffffff',
    color: '#2d1b69',
    accentColor: '#d69e2e',
  },
  'tech-dark': {
    backgroundColor: '#ffffff', // Force white for print
    color: '#000000',
    accentColor: '#00ff88',
  },
  'clean-white': {
    backgroundColor: '#ffffff',
    color: '#000000',
    accentColor: '#000000',
  },
}; 