version: '3.8'

services:
  # Go API Service
  cvilo-api:
    build:
      context: ./cvilo-api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./cvilo-api/.env
    environment:
      - GIN_MODE=debug
    volumes:
      - ./cvilo-api:/app
      - /app/tmp
    networks:
      - cvilo-network
    restart: unless-stopped

  # React Client Dashboard
  cvilo-clientarea:
    build:
      context: ./cvilo-clientarea
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3009:3009"
    environment:
      - VITE_API_URL=http://localhost/api
    volumes:
      - ./cvilo-clientarea:/app
      - /app/node_modules
    depends_on:
      - cvilo-api
    networks:
      - cvilo-network
    restart: unless-stopped

  # Next.js Landing Page (Development)
  cvilo-landing-nextjs:
    build:
      context: ./cvilo-landing-nextjs
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost/api
      - NODE_ENV=development
    volumes:
      - ./cvilo-landing-nextjs:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - cvilo-api
    networks:
      - cvilo-network
    restart: unless-stopped

  # Nginx Reverse Proxy (Development)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - cvilo-api
      - cvilo-clientarea
      - cvilo-landing-nextjs
    networks:
      - cvilo-network
    restart: unless-stopped

networks:
  cvilo-network:
    driver: bridge

volumes:
  app-data: 