version: '3.8'

services:
  # Go API Service
  cvilo-api:
    build:
      context: ./cvilo-api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - HOST=0.0.0.0
      - GIN_MODE=release
      - SQL_CONNECTION=cvilo.db
      - DB_PATH=cvilo.db
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - CORS_ORIGIN=https://app.cvilo.com
      - LINKEDIN_CLIENT_ID=77bwkyh7myeqpy
      - LINKEDIN_CLIENT_SECRET=your-linkedin-client-secret
      - LINKEDIN_REDIRECT_URL=https://api.cvilo.com/api/v1/linkedin/callback
      - USE_GITHUB_MODELS=true
      - GITHUB_TOKEN=your-github-token
      - GITHUB_MODELS_BASE_URL=https://models.github.ai/inference
      - OPENAI_API_KEY=your-openai-api-key
    volumes:
      - ./cvilo-api:/app
      - /app/tmp
    networks:
      - cvilo-network
    restart: unless-stopped

  # Go PDF Export Service (disabled)
  # cvilo-export:
  #   build:
  #     context: ./cvilo-export
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     - PORT=8082
  #   volumes:
  #     - ./cvilo-export:/app
  #     - /app/tmp
  #   networks:
  #     - cvilo-network
  #   restart: unless-stopped

  # React Client Dashboard
  cvilo-clientarea:
    build:
      context: ./cvilo-clientarea
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3009:3009"
    environment:
      - VITE_API_URL=https://api.cvilo.com/api
      # - VITE_EXPORT_URL=https://api.cvilo.com/export  # Disabled export service
    volumes:
      - ./cvilo-clientarea:/app
      - /app/node_modules
    depends_on:
      - cvilo-api
    networks:
      - cvilo-network
    restart: unless-stopped

  # React Landing Page (disabled due to build issues)
  # cvilo-landing:
  #   build:
  #     context: ./cvilo-landing
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - VITE_API_URL=https://cvilo.com/api
  #   volumes:
  #     - ./cvilo-landing:/app
  #     - /app/node_modules
  #   depends_on:
  #     - cvilo-api
  #   networks:
  #     - cvilo-network
  #   restart: unless-stopped

  # Next.js Landing Page
  cvilo-landing-nextjs:
    build:
      context: ./cvilo-landing-nextjs
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.cvilo.com/api
      - NODE_ENV=production
    volumes:
      - ./cvilo-landing-nextjs:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - cvilo-api
    networks:
      - cvilo-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - cvilo-api
      # - cvilo-export  # Disabled export service
      - cvilo-clientarea
      # - cvilo-landing  # Disabled due to build issues
      - cvilo-landing-nextjs
    networks:
      - cvilo-network
    restart: unless-stopped

networks:
  cvilo-network:
    driver: bridge

volumes:
  app-data: 