name: CVILO Client Area - Build & Deploy

on:
  push:
    branches: [ main ]
    paths: [ 'cvilo-clientarea/**' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  BUILD_VERSION: ${{ github.sha }}
  BUILD_DATE: ${{ github.event.head_commit.timestamp }}
  API_BASE_URL: ${{ secrets.API_BASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}/cvilo-clientarea
        run: |
          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          docker build \
            --build-arg BUILD_VERSION=${{ env.BUILD_VERSION }} \
            --build-arg BUILD_DATE=${{ env.BUILD_DATE }} \
            --build-arg VITE_API_URL=${{ env.API_BASE_URL }} \
            -t $IMAGE_NAME_LOWER:latest \
            -t $IMAGE_NAME_LOWER:${{ env.BUILD_VERSION }} \
            ./cvilo-clientarea
          docker push $IMAGE_NAME_LOWER:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-cvilo-clientarea
      cancel-in-progress: true
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: github-deployer
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          envs: NON_INTERACTIVE
          script: |
            set -e
            cd /opt/cveeker
            git pull
            docker compose pull cvilo-clientarea
            docker compose up -d cvilo-clientarea