name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: github-deployer
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd /opt/cveeker
            docker compose pull
            docker compose up -d 